cibo/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_view
from coreapp import views, apis

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('restaurant/sign_in', auth_view.LoginView.as_view(template_name='restaurant/sign_in.html'), name='restaurant_sign_in'),
    path('restaurant/sign_out', auth_view.LogoutView.as_view(next_page='/'), name='restaurant_sign_out'),
    path('restaurant/sign_up', views.restaurant_sign_up, name='restaurant_sign_up'),
    path('restaurant/', views.restaurant_home, name='restaurant_home'),

    path('restaurant/account', views.restaurant_account, name='restaurant_account'),
    path('restaurant/meal', views.restaurant_meal, name='restaurant_meal'),
    path('restaurant/meal/add', views.restaurant_add_meal, name='restaurant_add_meal'),
    path('restaurant/meal/edit/<int:meal_id>', views.restaurant_edit_meal, name='restaurant_edit_meal'),
    path('restaurant/order', views.restaurant_order, name='restaurant_order'),
    path('restaurant/report', views.restaurant_report, name='restaurant_report'),

    path('api/customer/restaurants', apis.customer_get_restaurans),
    path('api/customer/meals/<int:restaurant_id>', apis.customer_get_meals),
    path('api/customer/order/add', apis.customer_add_order),
    path('api/customer/order/latest', apis.customer_get_latest_order),
    path('api/customer/order/latest_status', apis.customer_get_latest_order_status),
    path('api/customer/driver/location', apis.customer_get_driver_location),
    path('api/customer/payment_intent', apis.create_payment_intent),

    path('api/driver/order/ready', apis.driver_get_ready_orders),
    path('api/driver/order/pick', apis.driver_pick_order),
    path('api/driver/order/latest', apis.driver_get_latest_order),
    path('api/driver/order/complete', apis.driver_complete_order),
    path('api/driver/revenue', apis.driver_get_revenue),
    path('api/driver/location/update', apis.driver_update_location),
    path('api/driver/profile', apis.driver_get_profile),
    path('api/driver/profile/update', apis.driver_update_profile),

    path('api/restaurant/order/notification/<last_request_time>', apis.restaurant_order_notification),
]

coreapp/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Restaurant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='restaurant')
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.get_full_name()

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='driver')
    avatar = models.CharField(max_length=255)
    car_model = models.CharField(max_length=255, blank=True)
    plate_number = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.get_full_name()

class Meal(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='restaurant')
    name = models.CharField(max_length=255)
    short_description = models.TextField(max_length=500)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Order(models.Model):
    COOKING = 1
    READY = 2
    ONTHEWAY = 3
    DELIVERED = 4
    STATUS_CHOICES = (
        (COOKING, "Cooking"),
        (READY, "Ready"),
        (ONTHEWAY, "On the way"),
        (DELIVERED, "Delivered")
    )

    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.PROTECT)
    driver = models.ForeignKey(Driver, models.SET_NULL, blank=True, null=True)    
    address = models.CharField(max_length=500)
    total = models.IntegerField()
    status = models.IntegerField(choices=STATUS_CHOICES)
    created_at = models.DateTimeField(default=timezone.now)
    picked_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.id)

class OrderDetails(models.Model):
    order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name="order_details")    
    meal = models.ForeignKey(Meal, on_delete=models.PROTECT)    
    quantity = models.IntegerField()
    sub_total = models.IntegerField()

    def __str__(self):
        return str(self.id)

coreapp/forms.py
from django import forms
from django.contrib.auth.models import User
from coreapp.models import Restaurant, Meal

class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')

class RestaurantForm(forms.ModelForm):        
    class Meta:
        model = Restaurant
        fields = ('name', 'phone', 'address')

class AccountForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        exclude = ('restaurant',)

coreapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from coreapp.forms import AccountForm, MealForm, UserForm, RestaurantForm, MealForm
from coreapp.models import Meal, Order, Driver
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Sum, Count, Case, When

def home(request):
    return redirect(restaurant_home)

@login_required(login_url='/restaurant/sign_in')
def restaurant_home(request):
    return redirect(restaurant_order)#// render(request, 'restaurant/home.html', {})

def restaurant_sign_up(request):
    user_form = UserForm()
    restaurant_form = RestaurantForm()

    if request.method == "POST":
        user_form = UserForm(request.POST)
        restaurant_form = RestaurantForm(request.POST)

        if user_form.is_valid() and restaurant_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_restaurant = restaurant_form.save(commit=False)
            new_restaurant.user = new_user
            new_restaurant.save()
            login(request, authenticate(
                username = user_form.cleaned_data['username'],
                password = user_form.cleaned_data['password']
            ))

            return redirect(restaurant_home)

    return render(request, 'restaurant/sign_up.html', {
        'user_form': user_form,
        'restaurant_form': restaurant_form
    })    

@login_required(login_url='/restaurant/sign_in')
def restaurant_account(request):
    if request.method == "POST":
        account_form = AccountForm(request.POST, instance=request.user)
        restaurant_form = RestaurantForm(request.POST, instance=request.user.restaurant)

        if account_form.is_valid() and restaurant_form.is_valid():
            account_form.save()
            restaurant_form.save

    account_form = AccountForm(instance=request.user)
    restaurant_form = RestaurantForm(instance=request.user.restaurant)

    return render(request, 'restaurant/account.html', {
        "account_form": account_form,
        "restaurant_form": restaurant_form,
    })

@login_required(login_url='/restaurant/sign_in')
def restaurant_meal(request):
    meals = Meal.objects.filter(restaurant=request.user.restaurant).order_by("id")
    return render(request, 'restaurant/meal.html', {
        "meals": meals
    })

@login_required(login_url='/restaurant/sign_in')
def restaurant_add_meal(request):
    if request.method == 'POST':
        meal_form = MealForm(request.POST)
        if meal_form.is_valid():
            meal = meal_form.save(commit=False)
            meal.restaurant = request.user.restaurant
            meal.save()
            return redirect(restaurant_meal)
    meal_form = MealForm()
    return render(request, 'restaurant/add_meal.html', {
        'meal_form': meal_form
    })

@login_required(login_url='/restaurant/sign_in')
def restaurant_edit_meal(request, meal_id):
    instance = Meal.objects.get(id=meal_id)
    if request.method == 'POST':
        meal_form = MealForm(request.POST, instance=instance)
        if meal_form.is_valid():
            meal_form.save()
            return redirect(restaurant_meal)
    meal_form = MealForm(instance=instance)
    return render(request, 'restaurant/edit_meal.html', {
        'meal_form': meal_form
    })    

@login_required(login_url='/restaurant/sign_in')
def restaurant_order(request):
    if request.method == "POST":
        order = Order.objects.get(id=request.POST['id'])
        if order.status == Order.COOKING:
            order.status = Order.READY
            order.save()

    orders = Order.objects.filter(restaurant=request.user.restaurant).order_by("-id")
    return render(request, 'restaurant/order.html', {
        'orders': orders
    })

@login_required(login_url='/restaurant/sign_in')
def restaurant_report(request):
    from datetime import datetime, timedelta

    # weekdays
    revenue = []
    orders = []
    today = datetime.now()
    current_weekdays = [today + timedelta(days=i) for i in range(0 - today.weekday(), 7 - today.weekday())]

    for day in current_weekdays:
        delivered_orders = Order.objects.filter(
            restaurant=request.user.restaurant, 
            status=Order.DELIVERED, 
            created_at__year=day.year,
            created_at__month=day.month,
            created_at__day=day.day)

        revenue.append(sum(order.total for order in delivered_orders))
        orders.append(delivered_orders.count())

    # top 3 meals
    top3_meals = Meal.objects.filter(restaurant=request.user.restaurant)\
    .annotate(total_order=Sum("orderdetails__quantity"))\
    .order_by("-total_order")[:3]

    meal = {
        "labels": [meal.name for meal in top3_meals],
        "data": [meal.total_order or 0 for meal in top3_meals]
    }

    # top 3 drivers
    top3_drivers = Driver.objects.annotate(
        total_order=Count(Case(When(order__restaurant=request.user.restaurant, then = 1)))
    ).order_by("-total_order")[:3]

    driver = {
        "labels": [d.user.get_full_name() for d in top3_drivers],
        "data": [d.total_order for d in top3_drivers]
    }

    return render(request, 'restaurant/report.html', {
        "revenue": revenue, 
        "orders": orders,
        "meal": meal,
        "driver": driver
    })

coreapp/templates/restaurant/account.html
{% extends 'restaurant/base.html' %} 
{% load bootstrap4 %}

{% block title %} Account {% endblock title %} 

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">Account</h5>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form account_form %}
                        {% bootstrap_form restaurant_form %}
                        <button class="btn btn-black float-right" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

coreapp/templates/restaurant/add_meal.html
{% extends 'restaurant/base.html' %} 
{% load bootstrap4 %}

{% block title %} Add Meal {% endblock title %} 

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">Meal</h5>
            </div>
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% bootstrap_form meal_form %}
                    <button class="btn btn-black float-end" type="submit">Add</button>
                </form>
            </div>            
        </div>
    </div>
</div>
{% endblock body %}

coreapp/templates/restaurant/base.html
{% extends 'restaurant/layout.html' %}

{% block script %}
<script>
    $(document).ready(function() {
        var now = new Date();
        setInterval(function() {
            $.ajax({
                url: '/api/restaurant/order/notification/' + now.toISOString(),
                method: 'GET',
                success: function(data) {
                    if (data['notification'] === 0) {
                        $('.badge').text('');
                    } else {
                        $('.badge').text(data['notification']);
                    }
                }
            })
        }, 3000)
    })
</script>
{% endblock script %}

{% block sidebar %}

{% url 'restaurant_meal' as restaurant_meal_url %}
{% url 'restaurant_order' as restaurant_order_url %}
{% url 'restaurant_report' as restaurant_report_url %}
{% url 'restaurant_account' as restaurant_account_url %}

<div class="text-center mt-4">
    LOGO
    <br>
    <h5>{{ request.user.get_full_name }}</h5>
    <h6>{{ request.user.restaurant.name }}</h6>
</div>

<hr>

<div class="list-group">
    <span class="text-uppercase">Dashboard</span>    
    <a href="{% url 'restaurant_meal' %}" class="list-group-item {% if request.path == 'restaurant_meal_url' %}active{% endif %}">Meals</a>    
    <a href="{% url 'restaurant_order' %}" class="list-group-item {% if request.path == 'restaurant_order_url' %}active{% endif %}">Order <span class="badge bg-warning ml-2"></span> </a>    
    <a href="{% url 'restaurant_report' %}" class="list-group-item {% if request.path == 'restaurant_report_url' %}active{% endif %}">Report</a>
    
    <span class="text-uppercase">Profile</span>
    <a href="{% url 'restaurant_account' %}" class="list-group-item {% if request.path == 'restaurant_account_url' %}active{% endif %}">Account</a>
</div>

<div class="text-center my-3 mx-3">
    <a href="{% url 'restaurant_sign_up' %}" class="btn btn-warning btn-block">Logout</a>    
</div>
{% endblock sidebar %}

coreapp/templates/restaurant/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Eat | {% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body class="bg-gradient">
    <div class="container">
        <br>
        <div class="row justify-content-center">
            <div class="jumbotron">
                <h3 class="display-6 text-center">{% block heading %} {% endblock heading %} </h3>
                <br>
                {% block content %} {% endblock content %}                
            </div>
        </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

coreapp/templates/restaurant/edit_meal.html
{% extends 'restaurant/base.html' %} 
{% load bootstrap4 %}

{% block title %} Edit Meal {% endblock title %} 

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">Meal</h5>
            </div>
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% bootstrap_form meal_form %}
                    <button class="btn btn-black float-end" type="submit">Update</button>
                </form>
            </div>            
        </div>
    </div>
</div>
{% endblock body %}

coreapp/templates/restaurant/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <h1>Restaurant Page</h1>
    <div class="row">
      <div class="col-md-12 mb-2 text-center">
        <h4>Welcome, {{ user.username }}</h4>
        <a href="{% url 'restaurant_sign_out' %}">Logout</a>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

coreapp/templates/restaurant/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Eat | {% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round" type="text/css">

    <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        crossorigin="anonymous"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          {% block sidebar %} {% endblock sidebar %} 
        </div>

        <div class="col-md-10 offset-md-2 content">
          {% block body %} {% endblock body %}
        </div>
      </div>
    </div>
    
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

coreapp/templates/restaurant/meal.html
{% extends 'restaurant/base.html' %} 
{% block title %} Meals {% endblock title%} 
{% block body %}
<h1>Restaurant - Meals</h1>

<div class="row">
  <div class="col-md-10 offset-md-1">
    <div class="card shadow text-white mb-3 mt-5">
      <div class="card-header text-center">
        <h5 class="m-0 font-weight-bold text-black">Meals</h5>
      </div>
      <div class="card-body">
        <span class="float-end mb-3">
          <a href="{% url 'restaurant_add_meal' %}" class="btn btn-black">Add Meal</a>
        </span>

        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            {% for meal in meals %}
            <tr class="align-middle">
              <th scope="row">{{ meal.id }}</th>
              <td>
                <a href="{% url 'restaurant_edit_meal' meal.id%}"
                {{ meal.name }}
                </a>
              </td>
              <td>{{ meal.short_description }}</td>
              <td class="text-end">${{ meal.price }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

coreapp/templates/restaurant/order.html
{% extends 'restaurant/base.html' %} 

{% block title %} Order {% endblock title %} 

{% block body %}
<h1>Restaurant - Orders</h1>

<div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="card shadow text-white mb-3 mt-5">
        <div class="card-header text-center">
          <h5 class="m-0 font-weight-bold text-black">Orders</h5>
        </div>
        <div class="card-body">  
          <table class="table table-striped table-hover table-bordered">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Details</th>
                <th scope="col">Customer</th>
                <th scope="col">Driver</th>
                <th scope="col">Total</th>
                <th scope="col">Staus</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr class="align-middle">
                <th scope="row">{{ order.id }}</th>
                <td>
                    <ul>
                        {% for od in order.order_detals.all %}
                            <li>{{ od.meal.name }} : ${{ od.meal.price }} x {{ od.quantity }} = $ {{ od.sub_total }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>{{ order.customer }}</td>
                <td>{{ order.driver }}</td>
                <td class="text-end">${{ order.total }}</td>
                <td>${{ order.get_status_display }}</td>
                <td>
                    {% if order.status == 1 %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ order.id }}">
                        <button class="btn btn-black btn-sm">Ready</button>
                    </form>
                    {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}

coreapp/templates/restaurant/report.html
{% extends 'restaurant/base.html' %} 

{% block title %} Report {% endblock title %} 

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>
{% endblock %}

{% block body %}
<h1>Restaurant - Report</h1>

<div class="row">
    <div class="col-md-8">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">This week's revenue</h5>
                <div class="card-body">
                    
                    <canvas id="revenueChart" height="100"></canvas>
                    <script>
                    const ctx = document.getElementById('revenueChart').getContext('2d');
                    const revenueChart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                            datasets: [{
                                label: '$ Amount',
                                data: {{ revenue }},
                                backgroundColor: [
                                    'rgba(255, 99, 132, 0.2)',
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                ],
                                borderWidth: 1
                            }]
                        },                    
                    });
                    </script>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">Top 3 Meals</h5>
                <div class="card-body">
                    
                    <canvas id="mealsChart" height="80"></canvas>
                    <script>
                    const ctxMeals = document.getElementById('mealsChart').getContext('2d');
                    const mealsChart = new Chart(ctxMeals, {
                        type: 'pie',
                        data: {
                            labels: {{ meal.labels | safe }},
                            datasets: [{
                                data: {{ meal.data }},
                                backgroundColor: [
                                    'rgba(255, 99, 132)',
                                    'rgba(54, 162, 235)',
                                    'rgba(255, 205, 86)'
                                ],
                                hoverOffset: 4
                            }]
                        },                    
                    });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-8">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">Orders by week</h5>
                <div class="card-body">
                    
                    <canvas id="orderChart" height="100"></canvas>
                    <script>
                    const ctxOrder = document.getElementById('orderChart').getContext('2d');
                    const orderChart = new Chart(ctxOrder, {
                        type: 'line',
                        data: {
                            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                            datasets: [{
                                label: 'Orders',
                                data: {{ orders }},
                                backgroundColor: [
                                    'rgba(255, 99, 132)',
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132)',
                                ]                                
                            }]
                        },                    
                    });
                    </script>

                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card shadow text-white mb-3 mt-5">
            <div class="card-header text-center">
                <h5 class="m-0 font-weight-bold text-black">Top 3 Drivers</h5>
                <div class="card-body">
                    
                    <canvas id="driversChart" height="80"></canvas>
                    <script>
                    const ctxDriver = document.getElementById('driversChart').getContext('2d');
                    const driversChart = new Chart(ctxDriver, {
                        type: 'pie',
                        data: {
                            labels: {{ driver.labels | safe }},
                            datasets: [{
                                data: {{ driver.data }},
                                backgroundColor: [
                                    'rgba(255, 99, 132)',
                                    'rgba(54, 162, 235)',
                                    'rgba(255, 205, 86)'
                                ],
                                hoverOffset: 4
                            }]
                        },                    
                    });
                    </script>
                </div>
            </div>
        </div>
    </div>    
</div>
{% endblock body %}